sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        SncGndMdYCSWw1Ha2YMIhk9Mt2rjKPktpMRwKC5G+GeeUbzCHS9E3UVO4iauggE83Q4ZAK8Q+acOmirvPWfzYJhofrL6CxrDS2n1HuC7uO2aE+dSHMjtAxGmoihRkXS9uvqbuIBuKMOeeH5DmSFHcQma4/X1t0Thhln66aLeM9JcJgMIy+ykdeRlJds+hgtqhYo5+MwH6b5jiYrTdcmCRtd2DAX40dvo7kZL0JzgmhUp5W7RuKdqe6cjPYxB4g7O4H3D7Ll1ehp6AZU8EOGKTdxLg/F85WAwCkh5BoRudLIPlLdkk0LkPX78u8H+WRYul6hp9E7BJ0ZArGKzH0qS28C5Kmr4p/Q6JuIKXuBaCJiUFOfhEDKTZEgFw2m3td0VUfUtlX+nNjWYrmNRTPOAPV7ILNi0/sJtkFanmTEdiAAA1lgsk8z0Y4WDCay9AZDD280RlLnZVyHU3fU5Xpj7MPVGj8YOhBDWHrvOP75c3VqRxwFAqTbe9UyGbg5cCj5MhoPE77HxWqCzd3t91gwX7Ck9FWHxzw88Bir02uNOopXx3fE2GFfDSM9nk+HGsbSO/BYlMH7jTeRztnYbyGljjes8/TYoyRs92V3mjQJ+vkIKr6ib+aaR+78BrWAYG2L58B0/M7K3r1e5xbsOX/JTdU8bgmpXaRjhPnB3tShmh/8=
    - secure: >-
        wzZ+mTbRMt26n3B/5LvcY/AYFXiagB+5byGqfYwasNYhPEk/XDoSfgSobzRJREpwa8KAIHz4EiNWIZ/4ujbB0SzHmBwNQl9Mu8hkMjG8ODjohDjwTzmc0sZCjviygTCzR9Vbx2WOkovAdy9NMwComRkBAAydGSAwLqpoUPdHk2ZqEgt9bgYSlxFwwrZi2tQh5iZqqt2NhzZhrz+7yCRBAXdAw9bOXh4kCKfNeVBSilC5fK/rVykmmdFE5rGRQLpZ8GB/i4PuU4P74LxZGK9/ifm+uwftEpVu6ZZs/IY+FFPkHWzp9IIJv8Uq/tEG+GmIY5SNWVqkon+CIyt55PI6Gue2kQZ/qDIBZHIciyhAXH6D6+A29y4u8SSxKf7hR1LOupI92jR1/wnL8LK7O0hyXy3OgcLbkwrJ1sd53HabBoI979yp+TkPwJHFr11tZb7eBiGGutJsQSj/jWtlakuOSK0I7UuuXrkJpM1aLHIXhhMFaATS0cUEsFHEsZXBpjyZCq8/G8rbEQsXRsU0esPdZf8w/dRuHXn7XTDETS6D6dzo4Bm6eh+LiB+BIIvEKtm3bxrbuZqZojF+HdyIDOg5Re0IXzzeV4bBpzCz/3D6yFk9CErK4O3B6WMSEgvXTzP+hHim3I+afF6MMoYZoFK9eC1T38j4n4S4GYT+U9D08vs=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
